<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapitre 4 Inférer | Décrire et inférer. Une introduction intuitive à l’analyse quantitative avec R</title>
  <meta name="description" content="Chapitre 4 Inférer | Décrire et inférer. Une introduction intuitive à l’analyse quantitative avec R" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapitre 4 Inférer | Décrire et inférer. Une introduction intuitive à l’analyse quantitative avec R" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapitre 4 Inférer | Décrire et inférer. Une introduction intuitive à l’analyse quantitative avec R" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="décrire.html"/>
<link rel="next" href="references.html"/>
<style type="text/css">
p.abstract{
  text-align: center;
  font-weight: bold;
}
div.abstract{
  margin: auto;
  width: 90%;
}
</style>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Décrire et inférer</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Objectifs</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#les-logiciels"><i class="fa fa-check"></i><b>1.1</b> Les logiciels</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-générale-à-r.html"><a href="introduction-générale-à-r.html"><i class="fa fa-check"></i><b>2</b> Introduction générale à R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-générale-à-r.html"><a href="introduction-générale-à-r.html#les-packages"><i class="fa fa-check"></i><b>2.1</b> Les packages</a></li>
<li class="chapter" data-level="2.2" data-path="introduction-générale-à-r.html"><a href="introduction-générale-à-r.html#le-working-directory"><i class="fa fa-check"></i><b>2.2</b> Le «working directory»</a></li>
<li class="chapter" data-level="2.3" data-path="introduction-générale-à-r.html"><a href="introduction-générale-à-r.html#quelques-manipulations-initiales-avec-r"><i class="fa fa-check"></i><b>2.3</b> Quelques manipulations initiales avec R</a></li>
<li class="chapter" data-level="2.4" data-path="introduction-générale-à-r.html"><a href="introduction-générale-à-r.html#une-syntaxe-qui-roule-une-bonne-méthode-de-travail"><i class="fa fa-check"></i><b>2.4</b> Une syntaxe qui roule : une bonne méthode de travail</a></li>
<li class="chapter" data-level="2.5" data-path="introduction-générale-à-r.html"><a href="introduction-générale-à-r.html#charger-des-données"><i class="fa fa-check"></i><b>2.5</b> Charger des données</a></li>
<li class="chapter" data-level="2.6" data-path="introduction-générale-à-r.html"><a href="introduction-générale-à-r.html#voir-les-variables"><i class="fa fa-check"></i><b>2.6</b> Voir les variables</a></li>
<li class="chapter" data-level="2.7" data-path="introduction-générale-à-r.html"><a href="introduction-générale-à-r.html#tableau-croisé"><i class="fa fa-check"></i><b>2.7</b> Tableau croisé</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="décrire.html"><a href="décrire.html"><i class="fa fa-check"></i><b>3</b> Décrire</a>
<ul>
<li class="chapter" data-level="3.1" data-path="décrire.html"><a href="décrire.html#une-équation-pour-décrire-une-variable"><i class="fa fa-check"></i><b>3.1</b> Une équation pour décrire une variable</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="décrire.html"><a href="décrire.html#quest-ce-que-cette-équation"><i class="fa fa-check"></i><b>3.1.1</b> Qu’est-ce que cette équation?</a></li>
<li class="chapter" data-level="3.1.2" data-path="décrire.html"><a href="décrire.html#la-réponse"><i class="fa fa-check"></i><b>3.1.2</b> La réponse</a></li>
<li class="chapter" data-level="3.1.3" data-path="décrire.html"><a href="décrire.html#une-équation-générale-décrivant-la-variable"><i class="fa fa-check"></i><b>3.1.3</b> Une équation générale décrivant la variable?</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="décrire.html"><a href="décrire.html#les-types-de-variables-et-éviter-de-faire-nimporte-quoi"><i class="fa fa-check"></i><b>3.2</b> Les types de variables et éviter de faire n’importe quoi</a></li>
<li class="chapter" data-level="3.3" data-path="décrire.html"><a href="décrire.html#décrire-une-relation-entre-des-variables"><i class="fa fa-check"></i><b>3.3</b> Décrire une relation entre des variables</a></li>
<li class="chapter" data-level="3.4" data-path="décrire.html"><a href="décrire.html#la-régression-linéaire-simple-avec-une-variable-dichotomique"><i class="fa fa-check"></i><b>3.4</b> La régression linéaire simple avec une variable dichotomique</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="décrire.html"><a href="décrire.html#création-des-données"><i class="fa fa-check"></i><b>3.4.1</b> Création des données</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="décrire.html"><a href="décrire.html#la-régression-linéaire-simple-avec-une-variable-continue"><i class="fa fa-check"></i><b>3.5</b> La régression linéaire simple avec une variable continue</a></li>
<li class="chapter" data-level="3.6" data-path="décrire.html"><a href="décrire.html#la-régression-linéaire-avec-plusieurs-variables-indépendantes"><i class="fa fa-check"></i><b>3.6</b> La régression linéaire avec plusieurs variables indépendantes</a></li>
<li class="chapter" data-level="3.7" data-path="décrire.html"><a href="décrire.html#la-régression-linéaire-un-exemple-avec-des-données-réelles"><i class="fa fa-check"></i><b>3.7</b> La régression linéaire, un exemple avec des données réelles</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="inférer.html"><a href="inférer.html"><i class="fa fa-check"></i><b>4</b> Inférer</a>
<ul>
<li class="chapter" data-level="4.1" data-path="inférer.html"><a href="inférer.html#linférence-statistique-quelques-notions-théoriques"><i class="fa fa-check"></i><b>4.1</b> L’inférence statistique, quelques notions théoriques</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="inférer.html"><a href="inférer.html#le-théorème-de-la-limite-centrale"><i class="fa fa-check"></i><b>4.1.1</b> Le théorème de la limite centrale</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="inférer.html"><a href="inférer.html#léchantillonnage"><i class="fa fa-check"></i><b>4.2</b> L’échantillonnage</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="inférer.html"><a href="inférer.html#exemple-dune-élection-à-deux-partis-55-45"><i class="fa fa-check"></i><b>4.2.1</b> Exemple d’une élection à deux partis (55-45)</a></li>
<li class="chapter" data-level="4.2.2" data-path="inférer.html"><a href="inférer.html#exemple-dune-élection-serrée-51-49"><i class="fa fa-check"></i><b>4.2.2</b> Exemple d’une élection serrée (51-49)</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="inférer.html"><a href="inférer.html#du-sondage-à-la-population"><i class="fa fa-check"></i><b>4.3</b> Du sondage à la population</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="inférer.html"><a href="inférer.html#la-marge-derreur"><i class="fa fa-check"></i><b>4.3.1</b> La marge d’erreur</a></li>
<li class="chapter" data-level="4.3.2" data-path="inférer.html"><a href="inférer.html#la-différence-entre-deux-groupes-le-test-t"><i class="fa fa-check"></i><b>4.3.2</b> La différence entre deux groupes : Le Test <em>t</em></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Décrire et inférer. Une introduction intuitive à l’analyse quantitative avec R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inférer" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapitre 4</span> Inférer<a href="inférer.html#inférer" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Durant les vacances de Noël, j’étais dans un souper familial et nous discutions des élections américaines. Ma tante était debout devant le poêle et, pendant qu’elle faisait réchauffer une soupe, se disait surprise de l’élection de Trump. Après quelques soupirs, elle déclara :</p>
<blockquote>
<p>«En tout cas, moi les sondages, je commence à ne plus trop y croire. Tu ne peux pas prendre juste 1000 personnes sur une population de plusieurs millions et penser prévoir comment ils vont voter».</p>
</blockquote>
<p>Puis, après avoir bien brassé sa soupe, elle prit une petite cuillérée pour y goûter et, semblant juger qu’elle était adéquatement assaisonnée, lança avec assurance : «Ouin, elle va être bonne cette soupe-là!». Votre humble serviteur n’a pu s’empêcher de remarquer l’ironie de la situation : ma tante qui procédait avec assurance à l’échantillonnage de sa soupe, à peine quelques secondes après avoir déclaré ne pas croire à l’échantillonnage.</p>
<p>Ma tante a bien brassé la soupe pour que les éléments solides ne soient pas tous dans le fond du chaudron. Autrement dit, elle voulait, consciemment ou non, s’assurer que tous les éléments de sa soupe aient une chance égale d’aboutir dans sa cuiller. Puis elle en a pris une cuillérée et généralisa que ce que sa soupe goûtait dans sa cuiller devait être suffisamment semblable à ce que le reste la soupe dans le chaudron devait goûter. Dans le doute, ou si elle avait besoin de plus de précision, elle aurait pu prendre un second échantillon, mais elle ne l’a pas fait.</p>
<p>Pourtant, quelqu’un qui ne croit pas à l’échantillonnage aurait littéralement dû goûter à tout le chaudron pour savoir si sa soupe était correctement assaisonnée. Évidemment, aucun invité n’aurait eu de soupe et il est fort probable que ma tante n’aurait alors pas mangé de dinde, mais elle n’aurait alors pas eu à passer par l’échantillonnage. Cette petite anecdote peut vous faire sourire, mais réalisez que vous appliquez tous des techniques d’échantillonnage dans votre quotidien, autrement il vous serait tout simplement impossible d’accomplir plusieurs tâches pourtant simples et banales.</p>
<p>Évidemment, les êtres humains ne sont pas des molécules et il faut donc forcément en tenir compte lorsque nous analysons des statistiques qui sont influencées par le libre arbitre des individus. Cependant, en gardant en tête ces précautions, il demeure que les notions d’inférence statistiques peuvent aussi être appliquées aux comportements humains. Bien comprendre comment fonctionne l’inférence statistique vous permettra ensuite de mieux juger d’une variété de résultats qui, bien que «statistiquement adéquats», peuvent être critiquables étant donné que nous nous intéressons à des humains plutôt qu’à des molécules. Cependant, vous ne pourrez pas réellement poser un jugement informé sur ces situations sans bien comprendre l’inférence statistique. Malheuseuement, plusieurs comprennent mal ce qu’est l’inférence statistique et ont tendance à prendre la «significativité statistique» pour un absolu objectif qui peut se substituer au jugement du chercheur. Ce n’est <em>jamais</em> le cas. C’est à vous d’interpréter adéquatement ce que disent les chiffres et le fait que quelque chose soit «statistiquement significatif» ne constitue pas un sceau de véracité.</p>
<p>Afin de mieux saisir comment au juste fonctionne l’inférence statistique, nous allons utiliser l’exemple totalement fictif d’une élection dans laquelle le parti Rouge, dirigé par Gros-Cochon LeTapon-Tâteur, est en compétition avec le parti Bleu, dirigé par Madame Black-Berry duCourriel-Qui-Coule. Nous allons simuler les intentions de vote d’une population de 10 millions d’électeurs et nous prendrons ensuite aléatoirement des sondages de 1000 personnes dans cette population. Nous pourrons donc voir comment les sondages peuvent varier autour des véritables intentions de vote des 10 millions d’électeurs.</p>
<div id="linférence-statistique-quelques-notions-théoriques" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> L’inférence statistique, quelques notions théoriques<a href="inférer.html#linférence-statistique-quelques-notions-théoriques" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Toutes les variables ont une certaine distribution qui a une certaine forme. L’une des distributions les plus importantes en statistiques est la distribution normale. Une distribution normale a une moyenne de <span class="math inline">\(\mu\)</span> (prononcé «mu») et un écart-type de <span class="math inline">\(\sigma\)</span> (pronconé «sigma»). Vous verrez souvent l’expression : <span class="math inline">\(N\sim(\mu, \sigma)\)</span> pour dire qu’une variable est normalement distribuée avec une moyenne de <span class="math inline">\(\mu\)</span> et un écart-type de <span class="math inline">\(\sigma\)</span>. Bien sûr, la moyenne et l’écart-type d’une distribution peuvent varier. Voici quatre exemples de distributions normales. Les trois premières distributions ont une moyenne de 0, mais elles varient par leur écart-type; la distribution en bleu a quant à elle une moyenne de 1 et un écart-type de 1.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
<p>La mesure en unité d’écart-type est standardisée, c’est-à-dire que peu importe l’échelle de mesure originale, la distribution d’une variable peut être ramenée à une échelle mesurée en unité d’écart-type afin de pouvoir adéquatement comparer la distribution d’une variable à une autre variable mesurée différemment<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a>.</p>
<p>Par exemple, la figure suivante montre la distribution de deux variables <span class="math inline">\(N\sim(\mu, \sigma)\)</span>, une variable bleue et une variable rouge. L’échelle en noir est en unités d’écarts-types, alors que les échelles en bleu et en rouge peuvent être pensées comme deux possibilités d’échelles «originales» sur lesquelles les variables ont été mesurées. L’échelle en bleu va de 0 à 80 avec une moyenne de 40, celle en rouge de 40 à 160 avec une moyenne de 100 (on peut par exemple songer à la mesure du QI qui a aussi une moyenne de 100 et un écart-type de 15). Mais lorsque ces échelles sont ramenées en unité d’écarts-types, elles peuvent alors être adéquatement comparées. On remarque qu’en plaçant les échelles originales sur une échelle comparable, leur distribution est identique.</p>
<p>La raison tient à l’une des propriétés fondamentales de la loi normale : pour toute combinaison de moyenne et d’écart-type, il y aura toujours une proportion constante de cas entre la moyenne et un point quelconque situé à une certaine distance de la moyenne exprimée en écart-type. En observant la figure, on pourrait donc dire que, dans le cas de l’échelle bleue, il y a 95.4% des cas qui se situent entre 20 et 60, alors que 95% des cas se situent entre 85 et 115 dans le cas de la variable rouge.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>Nous savons qu’il y aura toujours exactement 68.3% des cas situés à <span class="math inline">\(\pm 1\sigma\)</span> (plus ou moins 1 écart-type). Il y aura aussi toujours 95.4% des cas situés à <span class="math inline">\(\pm 2\sigma\)</span> et 99.7% des cas situés à <span class="math inline">\(\pm3\sigma\)</span>. Cela sera vrai peu importe l’échelle de mesure originale utilisée pour mesurer une variable.</p>
<p>Cette propriété est vraie pour la distribution illustrée ici, mais elle le serait tout autant pour une distribution qui aurait une apparence plus aplatie. On pourrait «aplatir» la distribution de la figure, mais l’échelle des écarts-types bougerait avec elle. Imaginez que, pour aplatir la distribution, vous tiriez de chaque côté de l’axe des abscisses (x), cela aurait pour effet d’étirer chaque côté de la distribution et donc de l’aplatir, mais l’échelle suivrait elle aussi.</p>
<div id="le-théorème-de-la-limite-centrale" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Le théorème de la limite centrale<a href="inférer.html#le-théorème-de-la-limite-centrale" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Nous venons de voir rapidement l’importance de la distribution normale, mais pour comprendre l’inférence statistique, il est important de saisir qu’il existe trois types de distributions.</p>
<ol style="list-style-type: decimal">
<li>La distribution d’une population (N)
<ul>
<li>Lors d’un rescencement</li>
<li>Avec une moyenne <span class="math inline">\(\mu\)</span> et un écart-type <span class="math inline">\(\sigma\)</span></li>
</ul></li>
<li>La distribution d’un échantillon (n)
<ul>
<li>Lors d’un sondage</li>
<li>Avec une moyenne <span class="math inline">\(\bar{x}\)</span> (prononcé «x-barre») et un écart-type <span class="math inline">\(s\)</span></li>
</ul></li>
<li>La distribution de <em>tous les échantillons possibles</em> (distribution d’échantillonnage)
<ul>
<li>Toutes les combinaisons possibles des cas qu’il est possible de tirer pour produire un échantillon <em>n</em> d’une population <em>N</em>.</li>
</ul></li>
</ol>
<p>Les deux premiers types de distributions sont relativement intuitifs, le troisième est cependant plus difficile à saisir. Imaginons la population formée des éléments A, B, C, D, E (<em>N</em>=5) et que nous voulions tirer un échantillon de taille 2 (<em>n</em>=2). Dans ce cas, tous les échantillons possibles correspondent à toutes les paires de lettres qu’il est possible de tirer à partir de la population. Dans notre cas, il a a 10 échantillons possibles : AB, AC, AD, AE, BC, BD, BE, CD, CE et DE. Le nombre total d’échantillons possibles peut être calculé à partir du NcN :</p>
<p><span class="math display">\[Ncn=\frac{N!}{ n!(N-n)! }\]</span>
Le signe ! signifie «factoriel», il c’est-à-dire que nous multiplions entre eux la suite de nombre qui vient avec le premier nombre jusqu’à arriver à 1. Dans notre exemple, cela donne:
<span class="math display">\[\frac { 5! }{ 2!(5-2)! } =\frac { 5\times 4\times 3\times 2\times 1 }{ 2\times 1\quad (3\times 2\times 1) } =\frac { 120 }{ 12 } =10\]</span></p>
<p>Dans notre exemple, il y a donc 10 échantillons possibles de 2 lettres dans notre population de 5 lettres. Imaginons maintenant une situation habituelle avec un sondage de 1000 répondants (n=1000) pour une population de 5 millions d’électeurs (N=5 000 000). Tous les échantillons possibles signifient alors toutes les possibilités d’échantillons de <em>n</em>=1000 qu’il est possible de tirer d’une population de 5 millions d’individus. Deux échantillons ne différant que par 1 seul individu sont ici considérés comme deux échantillons possibles distincts. Dans ce cas, le nombre d’échantillons possibles donne :
<span class="math display">\[Ncn=\frac { N! }{ n!(N-n)! }\]</span>
<span class="math display">\[Ncn=\frac { 5 000 000! }{ 1000!(5 000 000-1000)! }\]</span>
<span class="math display">\[Ncn = 27 000 000 000 000 000 000 000 000 000 000 000 000 000\]</span>
Le nombre d’échantillons possibles est tellement gros que nous ne savons même pas comment au juste nous devrions dire ce nombre. Vous comprenez donc que cette idée de «tous les échantillons possibles» n’est que <em>théorique</em> et ne peut jamais réellement être appliquée. Cependant, sans pour autant que nous fassions la démonstration mathématique, sachez simplement que le théorème de la limite centrale nous apprend qu’au fur et à mesure que <em>le nombre d’échantillons augmente</em>, la moyenne d’une variété de paramètres de ces échantillons se rapprochera de plus en plus de la «vraie» valeur des paramètres dans la population.</p>
<p>Attention ici, nous ne parlons pas de la moyenne d’une variable <em>dans</em> un échantillon, mais de la <em>moyenne de la moyenne des échantillons</em>. Si par exemple nous nous intéressons à la taille moyenne des femmes d’une population donnée, nous prenons un premier échantillon de 100 femmes et nous obtenons une moyenne de 167cm. Nous prenons ensuite un second échantillon et nous obtenons une moyenne de 172cm. Un troisième échantillon nous donne une moyenne de 169 cm. À mesure que nous augmentons le nombre d’échantillons, la moyenne de ceux-ci (ici, la moyenne de 167, 172 et 169), qui revient à la moyenne des moyennes <em>dans</em> les échantillons_ se rapprochera de plus en plus de la «vraie» valeur dans la population. Mathématiquement, il pourrait être démontré que la moyenne de tous les échantillons possibles (la «moyenne échantillonnale») est égale à la moyenne de la population. Par ailleurs, la <em>disrtribution</em> de ces moyennes d’échantillons tendra à devenir normale et cela sera d’autant plus vrai que la taille des échantillons individuels sera grande.</p>
<p>Si la taille de l’échantillon est de 30 ou plus, les trois choses suivantes seront vraies :
- La moyenne de la distribution d’échantillonnage est identique à la moyenne de la population (<span class="math inline">\({ \mu }_{ \bar{x} }\)</span>=<span class="math inline">\(\mu\)</span>)
- La distribution d’échantillonnage suit une distribution normale.
- Son écart-type sera de <span class="math inline">\(\frac { \sigma }{ \sqrt { N } }\)</span></p>
</div>
</div>
<div id="léchantillonnage" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> L’échantillonnage<a href="inférer.html#léchantillonnage" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Afin d’illustrer le théorème de la limite centrale, qui est plus facile à saisir en le «voyant» à l’oeuvre qu’en tentant de le comprendre abstraitement, nous allons simuler des données d’une population de 10 millions de personnes et allons ensuite faire des «sondages» aléatoires dans cette population. Nous utiliserons deux scénarios. D’abord une élection entre deux partis, l’un étant réellement à 55% et l’autre à 45% d’intentions de vote dans la population. Puis nous simulerons une situation où la course entre ces deux partis est serrée, l’un étant réellement à 51% et l’autre à 49%. Nous observerons ce qui se produit lorsque nous augmentons la quantité de «sondages», et aussi de quoi ont l’air ces sondages lorsque le véritable écart entre les deux partis est relativement petit.</p>
<div id="exemple-dune-élection-à-deux-partis-55-45" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Exemple d’une élection à deux partis (55-45)<a href="inférer.html#exemple-dune-élection-à-deux-partis-55-45" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Nous simulons d’abord les données de la population de 10 millions d’individus</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="inférer.html#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créons les données de la population entière de 10M d&#39;électeurs.</span></span>
<span id="cb139-2"><a href="inférer.html#cb139-2" aria-hidden="true" tabindex="-1"></a>population <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="at">size=</span><span class="dv">10000000</span>, <span class="at">rep=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(.<span class="dv">55</span>,.<span class="dv">45</span>))</span>
<span id="cb139-3"><a href="inférer.html#cb139-3" aria-hidden="true" tabindex="-1"></a><span class="co"># L&#39;objet population contient donc 5 millions de lignes (individus) qui votent </span></span>
<span id="cb139-4"><a href="inférer.html#cb139-4" aria-hidden="true" tabindex="-1"></a><span class="co"># pour les différents partis dans les proportions décrites.</span></span>
<span id="cb139-5"><a href="inférer.html#cb139-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb139-6"><a href="inférer.html#cb139-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ftable</span>(population) <span class="co"># Voir le nombre d&#39;individus qui votent pour chaque parti.</span></span></code></pre></div>
<pre><code>## population       0       1
##                           
##            4499648 5500352</code></pre>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="inférer.html#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bien sûr, les proportions seraient plus informatives. Demandons-les à R. </span></span>
<span id="cb141-2"><a href="inférer.html#cb141-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(population)) <span class="co"># Pour en voir les proportions</span></span></code></pre></div>
<pre><code>## population
##         0         1 
## 0.4499648 0.5500352</code></pre>
<p>Nous voyons donc qu’il y a effectivement 55.00352% des gens qui ont l’entention de voter pour le parti bleu et 44.99648% qui ont l’intention de voter pour le parti rouge. Ce sont ici les <em>vraies</em> intentions de vote dans notre <em>population</em>. Imaginons maintenant que nous fassions un sondage aléatoire de 1000 individus dans cette population.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="inférer.html#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Faisons un premier sondage aléatoire de cette population </span></span>
<span id="cb143-2"><a href="inférer.html#cb143-2" aria-hidden="true" tabindex="-1"></a><span class="co"># avec un échantillon de 1000 personnes.</span></span>
<span id="cb143-3"><a href="inférer.html#cb143-3" aria-hidden="true" tabindex="-1"></a>sondage<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">sample</span>(population, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb143-4"><a href="inférer.html#cb143-4" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.1</span>))</span></code></pre></div>
<pre><code>## sondage.1
##     0     1 
## 0.473 0.527</code></pre>
<p>Nous obtenons ici qu’une proportion de 0.527 des «répondants» affirment vouloir voter pour le parti bleu et 0.473 pour le parti rouge. Faisons un deuxième sondage aléatoire.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="inférer.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Un deuxième sondage</span></span>
<span id="cb145-2"><a href="inférer.html#cb145-2" aria-hidden="true" tabindex="-1"></a>sondage<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">sample</span>(population, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb145-3"><a href="inférer.html#cb145-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.2</span>))</span></code></pre></div>
<pre><code>## sondage.2
##     0     1 
## 0.444 0.556</code></pre>
<p>Nous obtenons 55.6% pour le parti bleu et 44.4% pour le parti rouge. Faisons un troisième sondage.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="inférer.html#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Un troisième sondage</span></span>
<span id="cb147-2"><a href="inférer.html#cb147-2" aria-hidden="true" tabindex="-1"></a>sondage<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">sample</span>(population, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb147-3"><a href="inférer.html#cb147-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.3</span>))</span></code></pre></div>
<pre><code>## sondage.3
##     0     1 
## 0.475 0.525</code></pre>
<p>Ici, nous obtenons que 52.5% des répondants affirment vouloir voter pour le parti bleu, alors que 47.5 disent vouloir voter pour le parti rouge. Tentons un quatrième sondage.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="inférer.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Un quatrième sondage</span></span>
<span id="cb149-2"><a href="inférer.html#cb149-2" aria-hidden="true" tabindex="-1"></a>sondage<span class="fl">.4</span> <span class="ot">&lt;-</span> <span class="fu">sample</span>(population, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb149-3"><a href="inférer.html#cb149-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.4</span>))</span></code></pre></div>
<pre><code>## sondage.4
##     0     1 
## 0.441 0.559</code></pre>
<p>Avec ce quatrième sondage, nous obtenons que 55.9% des répondants affirment vouloir voter pour le parti bleu, alors que 44.1. Essayons un dernier sondage.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="inférer.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Un cinquième sondage</span></span>
<span id="cb151-2"><a href="inférer.html#cb151-2" aria-hidden="true" tabindex="-1"></a>sondage<span class="fl">.5</span> <span class="ot">&lt;-</span> <span class="fu">sample</span>(population, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb151-3"><a href="inférer.html#cb151-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.5</span>))</span></code></pre></div>
<pre><code>## sondage.5
##     0     1 
## 0.457 0.543</code></pre>
<p>Avec ce cinquième sondage, nous obtenons que 54.3% des répondants affirment vouloir voter pour le parti bleu, alors que 45.7.</p>
<p>Nous pourrions continuer ainsi à faire des sondages, mais remarquez deux choses : les résultats de chaque sondage ne sont par forcément «pile» sur les «vrais» chiffres dans la population (55% pour les bleus et 45% pour les rouges), mais ils tournent globalement autour de ceux-ci. Aussi, si nous faisons la moyenne des résultats obtenus dans ces cinq sondages, nous obtiendrions un résultat qui se rapprocherait encore plus de la vraie valeur. Essayons-le.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="inférer.html#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Moyenne des résultats des 5 sondages pour le parti bleu</span></span>
<span id="cb153-2"><a href="inférer.html#cb153-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.1</span>))[<span class="dv">2</span>],</span>
<span id="cb153-3"><a href="inférer.html#cb153-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.2</span>))[<span class="dv">2</span>],</span>
<span id="cb153-4"><a href="inférer.html#cb153-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.3</span>))[<span class="dv">2</span>],</span>
<span id="cb153-5"><a href="inférer.html#cb153-5" aria-hidden="true" tabindex="-1"></a>     <span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.4</span>))[<span class="dv">2</span>],</span>
<span id="cb153-6"><a href="inférer.html#cb153-6" aria-hidden="true" tabindex="-1"></a>     <span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.5</span>))[<span class="dv">2</span>]</span>
<span id="cb153-7"><a href="inférer.html#cb153-7" aria-hidden="true" tabindex="-1"></a>     )</span></code></pre></div>
<pre><code>## [1] 0.527</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="inférer.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Moyenne des résultats des 5 sondages pour le parti rouge</span></span>
<span id="cb155-2"><a href="inférer.html#cb155-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.1</span>))[<span class="dv">1</span>],</span>
<span id="cb155-3"><a href="inférer.html#cb155-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.2</span>))[<span class="dv">1</span>],</span>
<span id="cb155-4"><a href="inférer.html#cb155-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.3</span>))[<span class="dv">1</span>],</span>
<span id="cb155-5"><a href="inférer.html#cb155-5" aria-hidden="true" tabindex="-1"></a>     <span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.4</span>))[<span class="dv">1</span>],</span>
<span id="cb155-6"><a href="inférer.html#cb155-6" aria-hidden="true" tabindex="-1"></a>     <span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.5</span>))[<span class="dv">1</span>]</span>
<span id="cb155-7"><a href="inférer.html#cb155-7" aria-hidden="true" tabindex="-1"></a>     )</span></code></pre></div>
<pre><code>## [1] 0.473</code></pre>
<p>Nous n’avons que cinq sondages et notre moyenne n’est donc pas pile sur les vrais résultats de la population, mais nous nous en approchons beaucoup. Imaginons que nous fassions 50 sondages plutôt que seulement 5.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="inférer.html#cb157-1" aria-hidden="true" tabindex="-1"></a>data.sondages <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb157-2"><a href="inférer.html#cb157-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>){ <span class="co"># Ceci est un &quot;loop&quot;, nous faisons la même commande 50 fois</span></span>
<span id="cb157-3"><a href="inférer.html#cb157-3" aria-hidden="true" tabindex="-1"></a>    data.sondages[[i]] <span class="ot">&lt;-</span> <span class="fu">sample</span>(population, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb157-4"><a href="inférer.html#cb157-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb157-5"><a href="inférer.html#cb157-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb157-6"><a href="inférer.html#cb157-6" aria-hidden="true" tabindex="-1"></a>prop.sondages <span class="ot">=</span> <span class="fu">vector</span>()</span>
<span id="cb157-7"><a href="inférer.html#cb157-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span> <span class="sc">:</span><span class="dv">50</span>){</span>
<span id="cb157-8"><a href="inférer.html#cb157-8" aria-hidden="true" tabindex="-1"></a>    prop.sondages[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(data.sondages[[i]])</span>
<span id="cb157-9"><a href="inférer.html#cb157-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb157-10"><a href="inférer.html#cb157-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(prop.sondages)</span></code></pre></div>
<pre><code>## [1] 0.55378</code></pre>
<p>On pourrait difficilement faire mieux. Ceci dit, ici notre exemple posait que les vraies valeurs étaient à 55% et 45%, soit une différence de 10 points de pourcentage entre les deux partis. Dans la réalité, il arrive souvent que les vraies intentions de vote soient beaucoup plus serrées. Imaginons donc que nous une course très serrée dans laquelle le parti Bleu ne mène que par 2 points de pourcentage.</p>
</div>
<div id="exemple-dune-élection-serrée-51-49" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Exemple d’une élection serrée (51-49)<a href="inférer.html#exemple-dune-élection-serrée-51-49" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="inférer.html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créons les données de la population entière de 10M d&#39;électeurs.</span></span>
<span id="cb159-2"><a href="inférer.html#cb159-2" aria-hidden="true" tabindex="-1"></a>population.serre <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="at">size=</span><span class="dv">10000000</span>, <span class="at">rep=</span><span class="cn">TRUE</span>, <span class="at">prob=</span><span class="fu">c</span>(.<span class="dv">51</span>,.<span class="dv">49</span>))</span>
<span id="cb159-3"><a href="inférer.html#cb159-3" aria-hidden="true" tabindex="-1"></a><span class="co"># L&#39;objet population contient donc 5 millions de lignes (individus) qui votent </span></span>
<span id="cb159-4"><a href="inférer.html#cb159-4" aria-hidden="true" tabindex="-1"></a><span class="co"># pour les différents partis dans les proportions décrites.</span></span>
<span id="cb159-5"><a href="inférer.html#cb159-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb159-6"><a href="inférer.html#cb159-6" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(population)) <span class="co"># Pour en voir les proportions</span></span></code></pre></div>
<pre><code>## population
##         0         1 
## 0.4499648 0.5500352</code></pre>
<p>Faisons 50 sondages.</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="inférer.html#cb161-1" aria-hidden="true" tabindex="-1"></a>data.sondages_serre <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb161-2"><a href="inférer.html#cb161-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>){ <span class="co"># Ceci est un &quot;loop&quot;, même commande 50 fois i=1:50</span></span>
<span id="cb161-3"><a href="inférer.html#cb161-3" aria-hidden="true" tabindex="-1"></a>    data.sondages_serre[[i]] <span class="ot">&lt;-</span> <span class="fu">sample</span>(population.serre, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb161-4"><a href="inférer.html#cb161-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb161-5"><a href="inférer.html#cb161-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb161-6"><a href="inférer.html#cb161-6" aria-hidden="true" tabindex="-1"></a>prop.sondages_serre <span class="ot">=</span> <span class="fu">vector</span>()</span>
<span id="cb161-7"><a href="inférer.html#cb161-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span> <span class="sc">:</span><span class="dv">50</span>){</span>
<span id="cb161-8"><a href="inférer.html#cb161-8" aria-hidden="true" tabindex="-1"></a>    prop.sondages_serre[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(data.sondages_serre[[i]])</span>
<span id="cb161-9"><a href="inférer.html#cb161-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb161-10"><a href="inférer.html#cb161-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(prop.sondages_serre)</span></code></pre></div>
<pre><code>## [1] 0.512</code></pre>
<p>Vous voyez que nous obtenons une moyenne de nos 50 sondages qui ressemble à ce qui devrait être la vraie valeur de 0.51 pour le parti Bleu. Ceci étant, tous nos sondages n’ont pas, individuellement la même moyenne. Visualisons la distribution de nos sondages pour voir comment se sont répartis les résultats de tous les sondages.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="inférer.html#cb163-1" aria-hidden="true" tabindex="-1"></a>densite_50 <span class="ot">&lt;-</span> <span class="fu">density</span>(prop.sondages_serre)</span>
<span id="cb163-2"><a href="inférer.html#cb163-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb163-3"><a href="inférer.html#cb163-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(densite_50, </span>
<span id="cb163-4"><a href="inférer.html#cb163-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Distribution des résultats de 50 sondages&quot;</span>,</span>
<span id="cb163-5"><a href="inférer.html#cb163-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Fréquence&quot;</span>,</span>
<span id="cb163-6"><a href="inférer.html#cb163-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Proportion du vote du parti Bleu&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-80-1.png" width="672" /></p>
<p>Nous voyons que la distribution des résultats est presque normale, mais pas complètement. La plupart des sondages sont autour de la vraie valeur de 0.51, mais certains en sont plus éloignés. Imaginons maintenant que nous fassions 500 sondages plutôt que 50. Voyons voir.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="inférer.html#cb164-1" aria-hidden="true" tabindex="-1"></a>data.sondages_serre_500 <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb164-2"><a href="inférer.html#cb164-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">500</span>){</span>
<span id="cb164-3"><a href="inférer.html#cb164-3" aria-hidden="true" tabindex="-1"></a>    data.sondages_serre_500[[i]] <span class="ot">&lt;-</span> <span class="fu">sample</span>(population.serre, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb164-4"><a href="inférer.html#cb164-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb164-5"><a href="inférer.html#cb164-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb164-6"><a href="inférer.html#cb164-6" aria-hidden="true" tabindex="-1"></a>prop.sondages_serre_500 <span class="ot">=</span> <span class="fu">vector</span>()</span>
<span id="cb164-7"><a href="inférer.html#cb164-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">500</span>){</span>
<span id="cb164-8"><a href="inférer.html#cb164-8" aria-hidden="true" tabindex="-1"></a>    prop.sondages_serre_500[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(data.sondages_serre_500[[i]])</span>
<span id="cb164-9"><a href="inférer.html#cb164-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb164-10"><a href="inférer.html#cb164-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(prop.sondages_serre_500)</span></code></pre></div>
<pre><code>## [1] 0.509358</code></pre>
<p>Encore une fois, vous voyez que nous obtenons une moyenne très près de ce qui devrait être la vraie valeur de 0.51 pour le parti Bleu. Visualisons encore la distribution pour voir comment se sont répartis les résultats de tous les sondages.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="inférer.html#cb166-1" aria-hidden="true" tabindex="-1"></a>densite_500 <span class="ot">&lt;-</span> <span class="fu">density</span>(prop.sondages_serre_500)</span>
<span id="cb166-2"><a href="inférer.html#cb166-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb166-3"><a href="inférer.html#cb166-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(densite_500, </span>
<span id="cb166-4"><a href="inférer.html#cb166-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Distribution des résultats de 500 sondages&quot;</span>,</span>
<span id="cb166-5"><a href="inférer.html#cb166-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Fréquence&quot;</span>,</span>
<span id="cb166-6"><a href="inférer.html#cb166-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Proportion du vote du parti Bleu&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>Clairement, cette distribution est beaucoup plus près d’une distribution normale que ce que nous observions avec «seulement» 50 sondages. Essayons avec 5000.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="inférer.html#cb167-1" aria-hidden="true" tabindex="-1"></a>data.sondages_serre_5000 <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb167-2"><a href="inférer.html#cb167-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5000</span>){ </span>
<span id="cb167-3"><a href="inférer.html#cb167-3" aria-hidden="true" tabindex="-1"></a>    data.sondages_serre_5000[[i]] <span class="ot">&lt;-</span> <span class="fu">sample</span>(population.serre, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb167-4"><a href="inférer.html#cb167-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb167-5"><a href="inférer.html#cb167-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb167-6"><a href="inférer.html#cb167-6" aria-hidden="true" tabindex="-1"></a>prop.sondages_serre_5000 <span class="ot">=</span> <span class="fu">vector</span>()</span>
<span id="cb167-7"><a href="inférer.html#cb167-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5000</span>){</span>
<span id="cb167-8"><a href="inférer.html#cb167-8" aria-hidden="true" tabindex="-1"></a>    prop.sondages_serre_5000[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(data.sondages_serre_5000[[i]])</span>
<span id="cb167-9"><a href="inférer.html#cb167-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb167-10"><a href="inférer.html#cb167-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb167-11"><a href="inférer.html#cb167-11" aria-hidden="true" tabindex="-1"></a>densite_5000 <span class="ot">&lt;-</span> <span class="fu">density</span>(prop.sondages_serre_5000)</span>
<span id="cb167-12"><a href="inférer.html#cb167-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(densite_5000, </span>
<span id="cb167-13"><a href="inférer.html#cb167-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Distribution des résultats de 5000 sondages&quot;</span>,</span>
<span id="cb167-14"><a href="inférer.html#cb167-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Fréquence&quot;</span>,</span>
<span id="cb167-15"><a href="inférer.html#cb167-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Proportion du vote du parti Bleu&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>Clairement, la distribution de tous les sondages commence à prendre la forme d’une distribution normale avec une moyenne centrée autour de la vraie valeur de 0.51. Remarquez aussi que quelques sondages s’écartent de cette valeur, il y en a par exemple qui placent le parti Bleu à 0.46 et d’autres à 0.56, mais la très vaste majorité des sondages sont rapprochés de la vraie valeur de 0.51. Remarquez aussi qu’avec une différence de seulement 2 points de pourcentage entre les deux partis (dans la population), il y a quand même une grande quantité de sondages qui donnent moins de 50% des voix au parti Bleu, même si nous savons que ce dernier devrait être à 51%. Également, si nous comparons cette distribution avec 5000 sondages avec celle que nous avons obtenu avec 500 sondages, nous voyons aussi que la distribution avec 5000 sondages est plus resserrée, son écart-type est plus faible.</p>
<p>Cette démonstration devrait vous aider à saisir pourquoi il ne faut pas trop s’affoler avec des mouvements de 1, 2 ou 3 points de pourcentages d’un sondage à l’autre. Deux sondages menés la même journée et exactement de la même manière pourront donner des résultats différents. Ces variations inévitables sont le simple fait des aléas de l’échantillonnage statistique. Si l’on prend également en compte que, contrairement à nos 10 millions d’individus fictifs, les vrais citoyens peuvent décider de ne pas répondre (donc l’échantillonnage n’est jamais parfaitement aléatoire parce que la non-réponse peu être plus probable chez certains groupes) et que les maisons de sondage peuvent poser les questions de manière légèrement différente (ce qui peut également entraîner de légères variations dans les résultats), on comprendra qu’il n’y a vraiment pas de quoi écrire à sa mère pour des variations de quelques points de pourcentage.</p>
</div>
</div>
<div id="du-sondage-à-la-population" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Du sondage à la population<a href="inférer.html#du-sondage-à-la-population" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Évidemment, on ne fait jamais 5000 sondages, ni même 500. La plupart du temps, nous n’avons qu’un seul sondage à partir duquel on veut tirer des inférences sur une population entière. Comme nous l’avons vu, bien que les résultats des sondages tendent à se rapprocher des véritables valeurs d’une population, les aléas de l’échantillonnage font en sorte que les valeurs que nous obtenons dans un sondage donné dévient des vraies valeurs. Ainsi, il est plus prudent de construire une marge d’erreur autour des résultats du sondage.</p>
<div id="la-marge-derreur" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> La marge d’erreur<a href="inférer.html#la-marge-derreur" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Heureusement, grâce au théorème de la limite centrale, il est possible calculer avec précision un intervalle à l’intérieur duquel le véritable paramètre de la population devrait se retrouver, ce à un degré de confiance désiré. Généralement, le degré de confiance que nous visons est de 95%, c’est-à-dire que nous acceptons qu’il y ait 5% des chances que l’on se trompe en affirmant que le véritable paramètre de la population se retrouve à l’intérieur de l’interval que nous aurons calculé. Il convient cependant de remarquer que cette «ligne de démarcation» n’est que conventionnelle et a été fortement contestée récemment (voir notamment <span class="citation"><a href="#ref-Benjamin2017" role="doc-biblioref">Benjamin et al.</a> (<a href="#ref-Benjamin2017" role="doc-biblioref">2017</a>)</span> et la réponse de <span class="citation"><a href="#ref-Lakens2018" role="doc-biblioref">Lakens et al.</a> (<a href="#ref-Lakens2018" role="doc-biblioref">2017</a>)</span>).</p>
<p>Grâce au théorème de la limite centrale, nous savons que 95% des échantillons possibles donneront un pourcentage situé à plus ou moins 1.96 écart-types du vrai pourcentge. Nous savons cela grâce à la propriété de la distribution normale discutée plus haut : pour chaque combinaison de moyenne et d’écart-type, il y aura toujours une proportion constante de cas entre la moyenne et un point quelconque situé à une certaine distance de la moyenne exprimée en écart-type. Ici, nous voulons être certain à 95% de certidue, et donc nous savons que 95% des cas sont situés à l’intérieur de plus ou moins 1.96 écart-types. La figure suivante illustre la chose pour une distribution échantillonale ayant une moyenne de 0. 95% de tous les échantillons possibles nous donnerons un résultat situé dans la zone bleue.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-84-1.png" width="672" /></p>
<p>Suivant cela, si nous voulons estimer le pourcentage <span class="math inline">\(\pi\)</span> d’une population, nous pouvons le faire en utilisant le pourcentage <em>p</em> obtenu dans un sondage.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a> L’équation suivante permet de calculer la marge d’erreur autour de notre pourcentage <em>p</em> à l’intérieur de laquelle nous avons 95% des chances de trouver le véritable pourcentge <span class="math inline">\(\pi\)</span> dans la population.</p>
<p><span class="math display">\[\pi=p\pm 1,96 {\sigma}_{p}\]</span>
Où l’écart-type de la distribution échantillonnale <span class="math inline">\({\sigma}_{p}\)</span> est estimé à partir de l’écart-type <em>s</em> dans notre sondage.<br />
<span class="math display">\[{\sigma}_{p} = \frac { s }{ \sqrt { n }  }\]</span></p>
<div id="test-de-la-marge-derreur-du-pourcentage-55-45" class="section level4 hasAnchor" number="4.3.1.1">
<h4><span class="header-section-number">4.3.1.1</span> Test de la marge d’erreur du pourcentage (55-45)<a href="inférer.html#test-de-la-marge-derreur-du-pourcentage-55-45" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="inférer.html#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="co"># avec un échantillon de 1000 personnes.</span></span>
<span id="cb168-2"><a href="inférer.html#cb168-2" aria-hidden="true" tabindex="-1"></a>sondage<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">sample</span>(population, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb168-3"><a href="inférer.html#cb168-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.1</span>))</span></code></pre></div>
<pre><code>## sondage.1
##     0     1 
## 0.424 0.576</code></pre>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="inférer.html#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pour avoir l&#39;écart-type</span></span>
<span id="cb170-2"><a href="inférer.html#cb170-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(sondage<span class="fl">.1</span>) <span class="co"># sd() pour standard deviation</span></span></code></pre></div>
<pre><code>## [1] 0.4944375</code></pre>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="inférer.html#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculon Sigma_p</span></span>
<span id="cb172-2"><a href="inférer.html#cb172-2" aria-hidden="true" tabindex="-1"></a>sigma_p <span class="ot">&lt;-</span> <span class="fu">sd</span>(sondage<span class="fl">.1</span>)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">1000</span>)</span>
<span id="cb172-3"><a href="inférer.html#cb172-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb172-4"><a href="inférer.html#cb172-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculons l&#39;intervalle de confiance à 95%</span></span>
<span id="cb172-5"><a href="inférer.html#cb172-5" aria-hidden="true" tabindex="-1"></a>low_bound <span class="ot">&lt;-</span> <span class="fu">mean</span>(sondage<span class="fl">.1</span>)<span class="sc">-</span><span class="fl">1.96</span><span class="sc">*</span>sigma_p</span>
<span id="cb172-6"><a href="inférer.html#cb172-6" aria-hidden="true" tabindex="-1"></a>low_bound</span></code></pre></div>
<pre><code>## [1] 0.5453544</code></pre>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="inférer.html#cb174-1" aria-hidden="true" tabindex="-1"></a>hi_bound <span class="ot">&lt;-</span> <span class="fu">mean</span>(sondage<span class="fl">.1</span>)<span class="sc">+</span><span class="fl">1.96</span><span class="sc">*</span>sigma_p</span>
<span id="cb174-2"><a href="inférer.html#cb174-2" aria-hidden="true" tabindex="-1"></a>hi_bound</span></code></pre></div>
<pre><code>## [1] 0.6066456</code></pre>
<p>Donc, suivant notre calcul sur un sondage dans lequel le parti bleu avait 56% des intentions de vote, l’interval bas est de 0.5453544 et l’interval haut de 0.6066456. Suivant notre scénario, nous savons que le pourcentage <span class="math inline">\(\pi\)</span> réel d’intention de vote dans la population est de 55%, ce qui est bel et bien à l’intérieur de notre interval de confiance. Évidemment, ici nous avons l’avantage de connaître la véritable valeur du pourcentage de la population puisque nous l’avons nous-mêmes créé, ce n’est évidemment normalement pas le cas.</p>
</div>
<div id="test-de-la-marge-derreur-du-pourcentage-51-49" class="section level4 hasAnchor" number="4.3.1.2">
<h4><span class="header-section-number">4.3.1.2</span> Test de la marge d’erreur du pourcentage (51-49)<a href="inférer.html#test-de-la-marge-derreur-du-pourcentage-51-49" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Juste histoire de s’amuser, tentons aussi l’expérience avec notre scénario d’élection serrée.</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="inférer.html#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="co"># avec un échantillon de 1000 personnes.</span></span>
<span id="cb176-2"><a href="inférer.html#cb176-2" aria-hidden="true" tabindex="-1"></a>sondage<span class="fl">.1</span>_s <span class="ot">&lt;-</span> <span class="fu">sample</span>(population.serre, <span class="dv">1000</span>, <span class="at">replace=</span><span class="cn">FALSE</span>)</span>
<span id="cb176-3"><a href="inférer.html#cb176-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(sondage<span class="fl">.1</span>_s))</span></code></pre></div>
<pre><code>## sondage.1_s
##     0     1 
## 0.489 0.511</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="inférer.html#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pour avoir l&#39;écart-type</span></span>
<span id="cb178-2"><a href="inférer.html#cb178-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(sondage<span class="fl">.1</span>_s) <span class="co"># sd() pour standard deviation</span></span></code></pre></div>
<pre><code>## [1] 0.5001291</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="inférer.html#cb180-1" aria-hidden="true" tabindex="-1"></a>sigma_p <span class="ot">&lt;-</span> <span class="fu">sd</span>(sondage<span class="fl">.1</span>_s)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">1000</span>)</span>
<span id="cb180-2"><a href="inférer.html#cb180-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sondage<span class="fl">.1</span>_s)</span></code></pre></div>
<pre><code>## [1] 0.511</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="inférer.html#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculons l&#39;intervalle de confiance à 95%</span></span>
<span id="cb182-2"><a href="inférer.html#cb182-2" aria-hidden="true" tabindex="-1"></a>low_bound.s <span class="ot">&lt;-</span> <span class="fu">mean</span>(sondage<span class="fl">.1</span>_s)<span class="sc">-</span><span class="fl">1.96</span><span class="sc">*</span>sigma_p</span>
<span id="cb182-3"><a href="inférer.html#cb182-3" aria-hidden="true" tabindex="-1"></a>low_bound.s</span></code></pre></div>
<pre><code>## [1] 0.4800017</code></pre>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="inférer.html#cb184-1" aria-hidden="true" tabindex="-1"></a>hi_bound.s <span class="ot">&lt;-</span> <span class="fu">mean</span>(sondage<span class="fl">.1</span>_s)<span class="sc">+</span><span class="fl">1.96</span><span class="sc">*</span>sigma_p</span>
<span id="cb184-2"><a href="inférer.html#cb184-2" aria-hidden="true" tabindex="-1"></a>hi_bound.s</span></code></pre></div>
<pre><code>## [1] 0.5419983</code></pre>
<p>Ici, suivant notre calcul sur un sondage dans lequel le parti codé 1 avait 51.1 % des intentions de vote, l’intval bas est de 0.4800017 et l’interval haut de 0.5419983. Encore une fois, la vraie valeur du parti codé 1 est bien dans notre interval. Cependant, on remarque aussi que cet interval inclu la vraie valeur des intentions de vote du parti codé 0. Nous voyons donc que lorsque nous sommes devant une situation où les intentions de votes réelles dans la population sont très serrée, il est statistiquement très difficile d’établir avec confiance qu’un parti est réellement en avant d’un autre avec un seul sondage. la raison n’a ici rien à voir avec la fiabilité des méthodes statistiques elles-mêmes, mais est tout simplement lié à la nature même de la précision d’un échantillon et au fait que la précision requise pour «prédire» adéquatement le gagant d’une élection est beaucoup plus élevée quand une élection est serrée que lorsque’elle ne l’est pas.</p>
</div>
</div>
<div id="la-différence-entre-deux-groupes-le-test-t" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> La différence entre deux groupes : Le Test <em>t</em><a href="inférer.html#la-différence-entre-deux-groupes-le-test-t" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Le test-t est un test qui nous permet de déterminer si une différence observée entre deux groupes dans un échantillon peut être généralisée à l’ensemble de la population. Ici, plutôt que d’établir un intervalle à l’intérieur duquel on devrait raisonnablement s’attendre à trouver un paramètre d’intérêt dans notre population, on cherche plutôt à vérifier si la différence que l’on observe entre nos deux groupes dans le sondage existe bel et bien aussi dans la population. Autrement dit, nous nous intéressons à la <em>signification statistique</em> de la différence que nous observons dans l’échantillon.</p>
<p>Dans le cas de l’estimation de l’intervalle de confiance autour d’un pourcentage vu plus haut, nous n’avions pas réellement d’hypothèse à tester. Nous savions que le résultat d’un échantillon ne nous donne qu’une approximation de la valeur du paramètre dans la population et avons donc voulu avoir une approche plus rigoureuse pour estimer cette vraie valeur. Ici cependant, nous observons une différence entre deux groupes et nous voulons savoir si elle existe vraiment dans la population.</p>
<p>Intuitivement, puisque nous observons une différence entre nos deux groupes, nous pourrions dire que notre hypothèse est que les deux groupes doivent réellement être différents dans la population. Donc, mathématiquement :</p>
<p><span class="math display">\[\mu_1 \neq \mu_2\]</span>
Or, il n’y a pas de manière formelle de tester réellement cette hypothèse directement. Par contre, si nous l’inversons en formulant l’hypothèse nulle selon laquelle il n’y a pas de différence entre nos deux groupes, alors nous pouvons tester <em>l’improbabilité</em> de <span class="math inline">\(\mu_1 \neq \mu_2\)</span>. Donc, mathématiquement nous cherchons à vérifier si :</p>
<p><span class="math display">\[\mu_1=\mu2 \quad ou \quad  \mu_1-\mu2=0\]</span>
Si, suivant nos données, il est jugé trop <em>improbable</em> que <span class="math inline">\(\mu_1-\mu2=0\)</span> (moins de 5% des chances), alors inversement il sera crédible de croire que <span class="math inline">\(\mu_1 \neq \mu_2\)</span>.</p>
<p>Poser l’hypothèse nulle de cette manière est utile parce que, suivant notre connaissance de la distribution normale et du théorème de la limite centrale, nous savons de quoi devraient avoir l’air 95% des échantillons possibles dans une situation ou l’hypothèse nulle est vraie dans la population. Nous savons que les aléas de l’échantillnage produiront de la variation autour de la vraie valeur, mais nous savons de quoi devraient avoir l’air cette variation. En ce sens, si ce que nous observons dans nos données n’est <em>pas</em> conforme à ce que nous pourrions raisonnablement nous attendre d’observer dans 95% des échantillons possibles tirés d’une population où il n’y a <em>pas</em> de différence entre les deux groupes, alors nous jugerons crédible qu’il y ait réellement une différence dans la population.</p>
<p>Pour renforcer encore ce point : nous savons que dans une population ou <span class="math inline">\(mu_1=mu_2\)</span>, 95% des échantillons possibles nous donneront un résultat qui sera dans la zone bleue de la figure de distribution présentée plus haut. Si le résultat que nous observons se trouve à l’extérieur de cette zone bleue, dans les extrémités gauche et droite de la distribution, alors nous jugerons <strong>qu’il est trop improbable de tomber sur un échantillon qui nous montre une telle différence entre <span class="math inline">\(\mu_1\)</span> et <span class="math inline">\(\mu_2\)</span> s’il n’y en a pas dans la population. Nous jugerons alors que l’hypothèse nulle est trop improbable, donc peu crédible, et nous la rejetterons. Nous dirons donc que la différence que nous observons dans notre échantillon est «statistiquement significative»</strong>.</p>
<p>Revenons maintenant au tout premier exemple que nous avons utilisé au tout début à propos des notes de 100 étudiants. Imaginons que ces 100 étudiants soient un échantillon provenant d’une population de 10 000 étudiants ayant complété une épreuve ministérielle. Nous pourrions alors vouloir vérifier si la différence que nous avons observé entre les garçons et les filles était le seul fait de cet échantillon ou si cette différence existe réellement dans la population entière. Nous pourrions alors faire le tests-t.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="inférer.html#cb186-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histoire de se raffraîchire la mémoire</span></span>
<span id="cb186-2"><a href="inférer.html#cb186-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<pre><code>##      notes   sexe heures.etude fille
## 1 56.36004 garçon     3.429696     0
## 2 70.16088  fille     5.102714     1
## 3 61.71704  fille     4.780638     1
## 4 70.84951 garçon     5.656184     0
## 5 72.49611  fille     3.883307     1
## 6 84.08077 garçon     8.094016     0</code></pre>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="inférer.html#cb188-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Différence fille-garçon dans les notes?</span></span>
<span id="cb188-2"><a href="inférer.html#cb188-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(data<span class="sc">$</span>notes<span class="sc">~</span>data<span class="sc">$</span>sexe) <span class="co"># ~ pcq sexe est facteur binaire</span></span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  data$notes by data$sexe
## t = -5.4541, df = 92.215, p-value = 4.102e-07
## alternative hypothesis: true difference in means between group garçon and group fille is not equal to 0
## 95 percent confidence interval:
##  -14.333948  -6.681456
## sample estimates:
## mean in group garçon  mean in group fille 
##             57.52824             68.03595</code></pre>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="inférer.html#cb190-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Différence fille-garçon dans le temps d&#39;étude?</span></span>
<span id="cb190-2"><a href="inférer.html#cb190-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(data<span class="sc">$</span>heures.etude<span class="sc">~</span>data<span class="sc">$</span>sexe)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  data$heures.etude by data$sexe
## t = -4.9518, df = 90.354, p-value = 3.399e-06
## alternative hypothesis: true difference in means between group garçon and group fille is not equal to 0
## 95 percent confidence interval:
##  -2.2376079 -0.9562823
## sample estimates:
## mean in group garçon  mean in group fille 
##             4.360936             5.957881</code></pre>
<p>Un test-t vérifie l’improbabilité d’une valeur d’un échantillon en faisant l’hypothèse que cette valeur est <em>tirée d’une population dans laquelle cette valeur est de 0</em> (hypothèse nulle). La logique est très eaxtement la même lorsque nous évaluons la signification statistique des coefficients en régression linéaire. Visualisons les trois modèles que nous avions fait plus haut.</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="inférer.html#cb192-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = notes ~ sexe)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -20.2474  -7.3035  -0.6993   6.0207  26.5525 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   57.528      1.441  39.933  &lt; 2e-16 ***
## sexefille     10.508      1.925   5.458 3.63e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.556 on 98 degrees of freedom
## Multiple R-squared:  0.2331, Adjusted R-squared:  0.2253 
## F-statistic: 29.79 on 1 and 98 DF,  p-value: 3.627e-07</code></pre>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="inférer.html#cb194-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = notes ~ heures.etude)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -16.3271  -3.7251  -0.6483   4.1989  16.8874 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    36.981      1.957   18.90   &lt;2e-16 ***
## heures.etude    5.030      0.353   14.25   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.227 on 98 degrees of freedom
## Multiple R-squared:  0.6744, Adjusted R-squared:  0.6711 
## F-statistic:   203 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="inférer.html#cb196-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = notes ~ sexe + heures.etude)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.6705  -4.2615  -0.6981   3.9705  16.0712 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   37.3057     1.9227  19.403   &lt;2e-16 ***
## sexefille      3.1023     1.3758   2.255   0.0264 *  
## heures.etude   4.6372     0.3872  11.977   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.101 on 97 degrees of freedom
## Multiple R-squared:  0.6906, Adjusted R-squared:  0.6843 
## F-statistic: 108.3 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Notez que R nous renvoie une valeur <em>t</em>. Un coefficient est jugé significatif s’il est trop peu probale que le coefficient obtenu dans un échantillon soit tiré d’une population dans lequel il a la valeur de 0.</p>
<p>Vous voyez donc que le fait que quelque chose soit «statistiquement significatif» n’est absoluement pas une sorte de sceau magique démontrant la véracité absolu de quelque chose. Il s’agit tout simplement d’un critère conventionnel (95%) fondé sur l’improbabilité d’observer quelque chose dans un échantillon tiré d’une population dans laquelle nous faisons l’hypothèse que ce que nous pensons observer est faux. Au final, il s’agit donc simplement de savoir si ce que nous décrivons dans notre échantillon est aussi probablement vrai dans la population qui nous intéresse. Que ce soit dans un échantillon ou dans une population, ce n’est pas parce que deux groupes sont différents l’un de l’autre que cette différence est réellement <em>causée</em> par l’appartenance de groupe. Le fait que quelque chose soit «statistiquement significatif» veut simplement dire qu’il est très improbable que nous observions un certaine chose dans un échantillon si cela n’est pas aussi vrai dans la population. Au-delà d’établir l’association entre les deux phénomènes dans la population, la signification statistique ne nous dit rien de la causalité à proprement parler. En ce sens, il ne faut jamais interpréter la signification statistique comme établissant un rapport causal.</p>

</div>
</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Benjamin2017" class="csl-entry">
Benjamin, Daniel J., James O. Berger, Magnus Johannesson, Brian A. Nosek, E.-J. Wagenmakers, Richard Berk, Kenneth A. Bollen, et al. 2017. <span>“Redefine Statistical Significance.”</span> <em>Nature Human Behaviour</em> 2 (1): 6–10. <a href="https://doi.org/10.1038/s41562-017-0189-z">https://doi.org/10.1038/s41562-017-0189-z</a>.
</div>
<div id="ref-Lakens2018" class="csl-entry">
Lakens, Daniel, Federico Adolfi, Casper Albers, Farid Anvari, Matthew Apps, Shlomo Argamon, Marcel van Assen, et al. 2017. <span>“Justify Your Alpha,”</span> –. <a href="https://doi.org/10.17605/osf.io/9s3y6">https://doi.org/10.17605/osf.io/9s3y6</a>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="5">
<li id="fn5"><p>L’écart-type est calculé par la racine carrée de la moyenne des carrés des écarts entre chaque observation et la moyenne. Soit : <span class="math inline">\(\sqrt{\frac{\Sigma({x}_{i}-\mu)^2}{N}}\)</span>, où <span class="math inline">\(\chi\)</span> représente une observation <em>i</em>, <span class="math inline">\(\mu\)</span> la moyenne des observations <span class="math inline">\(\chi_i\)</span> et N Le nombre de cas.<a href="inférer.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>Les équations pour l’estimation d’une moyenne sont similaires. Il suffit de remplacer les signes appropriés, ce qui donne <span class="math inline">\(\mu=\bar{x}\pm 1.96 {\sigma}_{\bar{x}}\)</span>, où <span class="math inline">\({\sigma}_{\bar{x}}=\frac{s}{\sqrt{ n }}\)</span><a href="inférer.html#fnref6" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="décrire.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/03-inferer.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
